### ISSUE TITLE
Fork mysql-connector-net

### ISSUE THREAD

**Issue by IntelOrca** [SapientGuardian/mysql-dnxcore50#2]
It looks like mysql-connector-net was recently added to GitHub:
https://github.com/mysql/mysql-connector-net/tree/7.0

So perhaps the changes in this repository could be moved to a fork of the above repository. Then the changes can be rebased more easily on top of the latest official repository.

**Comment by SapientGuardian** [comment]
That's a great idea. As #1 points out, this repo is in an odd state at the moment. The RC1 packages don't have the right classes for targeting this against dotnet5_4, and the early RC2 packages I used to build the current version don't exist anymore. 

When RC2 is released (soon, I hope!) I'll fork the mysql-connector-net repo and re-apply these changes targeting netstandard1.5. I'll probably try to preserve the unit tests this time - I think nunit has coreclr support now.

**Comment by SapientGuardian** [comment]
Even though RC2 hasn't been finalized, I've gone ahead and forked the official repo and made the changes to target netstandard 1.5. It compiles, but I haven't done any testing beyond that yet. I'm going to leave the mysql-dnxcore50 repo up for now, since there are projects that depend on it.

https://github.com/SapientGuardian/mysql-connector-net-netstandard1.5
